on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

name: 🚀 Make data

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Make data
        run: python make_data.py
      - name: Install R dependencies
        run: Rscript -e 'install.packages(c("ggplot2", "hexbin"), dependencies = TRUE)'
      - name: Make graph
        run: Rscript -e 'source("make_graph.R")'
      - name: Commit results
        run: |
          git commit attractor_points.png attractor_density.png -m 'create data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
