on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * *'

name: 🚀 Make data

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          cache: 'pip'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run script
        run: python make_data.py
      - name: Commit results
        run: |
          git commit data.csv -m 'create data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
